package pl.admund.MVM_Client.XMLUtils;

public enum XMLType 
{
	CHECK_HTTP,
	LOGIN_HTTP,
	CRT_PLR_HTTP,
	GET_SQD_HTTP,
	GET_TABLE_HTTP,
	GET_MSG_HTTP,
	SEND_MSG_HTTP,
	DEL_MSG_HTTP,
	GET_PROFILE_HTTP,
	
	SET_SQD_HTTP,
	MATCH_PROP_HTTP,
	MATCH_ACCEPT_HTTP,
	MATCH_NEXT_HTTP,
	GET_TEAM_INFO_HTTP,
	
//-------TACTIC------
	GET_TEAM_TACTIC_HTTP,
	SET_TEAM_TACTIC_HTTP,
}
